### ISSUE TITLE
Update transcript selection priority rules

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/uta-tools#77]
Currently we have:
1. MANE Select
2. MANE Plus Clinical
3. Longest Compatible Remaining Transcript

We should change to:
1. MANE Select
2. MANE Plus Clinical
3. Longest Compatible Remaining Transcript
4. The first-published transcript among those transcripts meeting criterion in #<span></span>3
  _Note: first-published means lowest-numbered accession for RefSeq/Ensembl_

We also need to fix #<span></span>3. It should be based off the largest number of nucleotides on an exon rather than longest genomic coordinates. @ahwagner may have a better way to explain this.

**Comment by ahwagner** [comment]
> We also need to fix #3. It should be based off the largest number of nucleotides on an exon rather than longest genomic coordinates. @ahwagner may have a better way to explain this.

I would say it is the longest compatible cDNA sequence. Another way of thinking about this is just a python `len()` call on the sequence associated with an NM_* or ENST* identifier.
